service: github-webhook
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:*:*:*"
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - '*/*'
    minimumCompressionSize: 1024
    metrics: true
    logging: true
    dataTraceEnabled: true
    description: 'API Gateway for GitHub Webhook'
    endpointConfiguration: REGIONAL
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: 'execute-api:Invoke'
        Resource: 'execute-api:/*'
        Condition:
          IpAddress:
            aws:SourceIp:
              - '0.0.0.0/0'

package:
  individually: true
  patterns:
    - '!./**'
    - 'tooling/github-webhook/dist/**/*'

functions:
  github-webhook:
    handler: tooling/github-webhook/dist/app.lambdaHandler
    events:
      - http:
          path: /webhook
          method: post
          cors:
            origin: '*'
          request:
            passThrough: WHEN_NO_MATCH
          response:
            headers:
              Content-Type: "'application/json'"
              Access-Control-Allow-Origin: "'*'"
    environment:
      NODE_ENV: ${opt:stage, 'dev'}
    timeout: 30
    memorySize: 256
    reservedConcurrency: 10