

service: github-webhook
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

package:
  individually: true
  exclude:
    - ./**

functions:
  hello:
    handler: tooling/github-webhook/dist/app.lambdaHandler
    package:
      include:
        - 'tooling/github-webhook/dist/**/*'