

service: github-webhook
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

package:
  individually: true
  exclude:
    - ./**

functions:
  github-webhook:
    handler: tooling/github-webhook/dist/app.lambdaHandler
    events:
      - http:
        method: '*'
        path: /path
        cors: true
    package:
      include:
        - 'tooling/github-webhook/dist/**/*'